# Generated by Django 5.1.2 on 2024-10-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_testtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
